# Generated by Django 4.0.4 on 2022-05-19 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=25)),
                ('brand_model', models.CharField(max_length=25)),
                ('cpu_type', models.CharField(choices=[('i3', 'Intel Core i3'), ('i5', 'Intel Core i5'), ('i7', 'Intel Core i7'), ('i9', 'Intel Core i9'), ('Duos', 'Intel Core Duos'), ('Cel', 'Intel Celeron'), ('Cen', 'Intel Centrino'), ('AMD', 'AMD CPU')], max_length=25)),
                ('cpu_gen', models.CharField(choices=[('1st', 'First Gen'), ('2nd', 'Second Gen'), ('3rd', 'Third Gen'), ('4th', 'Forth Gen'), ('5th', 'Fifth Gen'), ('6th', 'Sixth Gen'), ('7th', 'Seventh Gen'), ('8th', 'Eighth Gen'), ('9th', 'Ninth Gen'), ('10th', 'Tenth Gen')], max_length=25)),
                ('ram', models.IntegerField(choices=[(1, '1GB'), (2, '2GB'), (4, '4GB'), (6, '6GB'), (8, '8GB'), (16, '16GB'), (32, '32GB')])),
                ('storage', models.CharField(choices=[('HDD', 'Hard Disk Drive'), ('SSD', 'Solid State Drive'), ('SSHD', 'SS + HD Drive')], max_length=15)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.laptop')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('order_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='store.orderitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
