# Generated by Django 4.0.4 on 2022-05-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
